package enterkomputer.utilities;

public class ListKategori {
    private String listAllKategori = "Processor <processor>\n"
            + "Motherboard <motherboard>\n"
            + "Harddisk <harddisk>\n"
            + "SSD <ssd>\n"
            + "RAM:\n"
            + "PC RAM <memoryram>\n"
            + "Notebook RAM <memoryramnotebook>\n"
            + "VGA Card <vga>\n"
            + "Power Supply <psu>\n"
            + "Casing PC <casing>\n"
            + "LCD <lcd>\n"
            + "Optical Drive <optical>\n"
            + "Keyboard & Mouse <keyboard>\n"
            + "Software & OS <software>\n"
            + "Cooler & Fan  <coolerfan>\n"
            + "Flashdisk <flashdisk>\n"
            + "Memory Card<memorycard>\n"
            + "UPS & Stabilizer <ups>\n"
            + "Networking <networking>\n"
            + "Modem Portable (GSM & CDMA) <modem>\n"
            + "AIO PC & PC Branded <allinone>\n"
            + "Server <server>\n"
            + "NAS <nas>\n"
            + "Office <office>\n"
            + "Accessories:\n"
            + "Powerbank & Mobile Adaptor / Charger <powerbank>\n"
            + "Enclosure/Docking/Harddisk Case Protector Cable / Converter / KVM / Splitter Thermal Pasta Webcam USB HUB,Card Reader,PCI / USB Converter,Bluetooth Dongle TV Tuner & TV Box & MP3 Gamepad, Steering, Presenter, Gaming Glasses Function Panel & Front Panel Converter Neon CCFL\n"
            + "Audio Speaker Headset Sound Card\n"
            + "Printer & Catridge Printer Cartridge & Toner\n"
            + "NoteBook & Accessories Notebook & Ultrabook Notebook Cooler, Battery, Adaptor, Sparepart, Accessories\n"
            + "Tablet & Smartphone Tablet Smartphone Tempered Glass & Acc\n"
            + "Digital Drawing Tablet\n"
            + "Media Player\n"
            + "Projector\n"
            + "Drone";
}
